import {
  GitBranch, Layout, Layers, Zap, Terminal, Code2, Database, Server,
  Rocket, Lock, Cloud, Target, Award, Video, Languages, Briefcase,
  GraduationCap
} from 'lucide-react';

export const modules = [
  {
    id: 1, title: 'WEEK 0 — Internet Working + Setup + Git/GitHub', icon: GitBranch,
    topics: [
      'How internet works (DNS, HTTP/HTTPS, client-server model)',
      'How websites load in browser (request → response cycle)',
      'VS Code setup + extensions (Prettier, Live Server, ESLint basics)',
      'Terminal basics (cd, ls, mkdir, rm, touch)',
      'Git & GitHub: init, add, commit, push, pull, clone, branch basics',
      'GitHub workflow (real developer flow)',
      'Folder structure in real projects',
    ],
    duration: '1 week', color: '#22d3ee',
  },
  {
    id: 2, title: 'HTML (HyperText Markup Language)', icon: Layout,
    topics: [
      'What is HTML and why it exists',
      'HTML document structure (doctype, head, body)',
      'Text elements (h1–h6, p, br, hr)',
      'Layout fundamentals: div (block container), span (inline container)',
      'Semantic HTML: header, nav, section, article, aside, footer',
      'Links and navigation (a tag, routing concept)',
      'Media: img, audio, video',
      'Lists (ul, ol, li)',
      'Forms: input types (text, email, password, number, file), textarea, select, option, label, form validation basics',
      'SEO basics (meta tags, OG tags)',
      'Accessibility basics (alt, aria-label)',
      'Page structuring mindset (layout thinking)',
    ],
    duration: '1 week', color: '#fb923c',
  },
  {
    id: 3, title: 'CSS (Cascading Style Sheets)', icon: Layers,
    topics: [
      'What is CSS and how it connects with HTML',
      'CSS syntax and selectors',
      'Colors (hex, rgb, rgba, hsl)',
      'Typography (fonts, spacing, weights)',
      'Box model (margin, padding, border, content)',
      'Display system: block, inline, inline-block, none',
      'Positioning: relative, absolute, fixed, sticky',
      'Z-index layering',
      'Flexbox (complete mastery)',
      'CSS Grid (complete layout system)',
      'Responsive design: media queries, mobile-first design',
      'Animations & transitions',
      'Hover effects & micro-interactions',
      'CSS architecture basics',
    ],
    duration: '1.5 weeks', color: '#818cf8',
  },
  {
    id: 4, title: 'TAILWIND CSS + BOOTSTRAP', icon: Zap,
    topics: [
      'Why CSS frameworks exist',
      'Tailwind CSS: utility-first concept, spacing system, flex/grid utilities, responsive classes, dark mode',
      'Bootstrap: grid system, components (navbar, cards, modals)',
      'Rapid UI building techniques',
      'Design consistency using utilities',
    ],
    duration: '0.5 weeks', color: '#38bdf8',
  },
  {
    id: 5, title: 'JAVASCRIPT (ADVANCED FRONTEND LOGIC)', icon: Terminal,
    topics: [
      'JavaScript runtime understanding',
      'Variables (let, const, var)',
      'Data types & type coercion',
      'Operators & expressions',
      'Control flow (if/else, switch)',
      'Loops (for, while, map, filter, reduce, forEach)',
      'Functions: scope, closures, callbacks',
      'Objects & arrays deep understanding',
      'DOM manipulation: querySelector, event delegation, dynamic rendering',
      'Events system: bubbling & capturing',
      'Async JavaScript: promises, async/await, fetch API',
      'Error handling',
      'LocalStorage / SessionStorage',
      'ES6+ features (spread, destructuring, modules)',
    ],
    duration: '2 weeks', color: '#fbbf24',
  },
  {
    id: 6, title: 'REACT JS (ADVANCED FRONTEND ENGINEERING)', icon: Code2,
    topics: [
      'React architecture',
      'JSX deep understanding',
      'Components design system',
      'Props vs State',
      'Hooks: useState, useEffect, useRef, useMemo, useCallback, useReducer',
      'Custom Hooks (real-world patterns)',
      'Context API (state management)',
      'Zustand (modern state management)',
      'React Router (advanced routing)',
      'API integration patterns',
      'Performance optimization',
      'Component reusability architecture',
      'Project: Advanced dashboard / SaaS frontend system',
    ],
    duration: '2.5 weeks', color: '#818cf8',
  },
  {
    id: 7, title: 'SUPABASE (FULL BACKEND AS A SERVICE)', icon: Database,
    topics: [
      'Supabase architecture',
      'Authentication: email/password, OAuth (Google, GitHub), SSO basics',
      'Database: tables, relations, Row Level Security (RLS)',
      'Real-time subscriptions',
      'Edge functions',
      'File storage system',
      'Custom email',
      'Database policies',
    ],
    duration: '1 week', color: '#34d399',
  },
  {
    id: 8, title: 'EXPRESS JS (ADVANCED BACKEND ENGINEERING)', icon: Server,
    topics: [
      'Node.js architecture',
      'Express server setup',
      'REST API design (production style)',
      'Middleware system',
      'Authentication: JWT, bcrypt password hashing',
      'Authorization roles system',
      'File upload: multer, Cloudinary integration',
      'Error handling architecture',
      'Logging systems',
      'API security best practices',
    ],
    duration: '1.5 weeks', color: '#10b981',
  },
  {
    id: 9, title: 'MONGODB + MONGOOSE (ADVANCED DATABASE SYSTEMS)', icon: Database,
    topics: [
      'Databases: SQL VS NoSQL',
      'NoSQL deep understanding',
      'MongoDB architecture',
      'Collections & documents',
      'Mongoose schemas',
      'Validation system',
      'CRUD operations',
      'Population (joins in MongoDB)',
      'Indexing basics',
      'Middleware (pre/post hooks)',
      'Aggregation pipeline basics',
    ],
    duration: '1 week', color: '#6cc24a',
  },
  {
    id: 10, title: 'NEXT.JS (PRODUCTION FULL STACK FRAMEWORK)', icon: Rocket,
    topics: [
      'App router architecture',
      'Server vs client components',
      'SSR / SSG / ISR',
      'API routes',
      'Middleware system',
      'Authentication patterns',
      'Performance optimization',
      'Full stack integration patterns',
      'Deployment readiness',
    ],
    duration: '1.5 weeks', color: '#f1f5f9',
  },
  {
    id: 11, title: 'TYPESCRIPT (PROFESSIONAL TYPE SAFETY)', icon: Lock,
    topics: [
      'Why TypeScript exists',
      'Primitive types',
      'Interfaces',
      'Type aliases',
      'Generics',
      'Functions typing',
      'React + TypeScript integration',
      'API typing systems',
    ],
    duration: '1 week', color: '#3178c6',
  },
  {
    id: 12, title: 'DEPLOYMENT (PRODUCTION ENGINEERING)', icon: Cloud,
    topics: [
      'Vercel deployment',
      'Netlify deployment',
      'Railway deployment',
      'Digital Ocean / AWS / Azure overview',
      'Environment variables',
      'CI/CD basics',
      'Build optimization',
      'Domain setup',
    ],
    duration: '0.5 weeks', color: '#a78bfa',
  },
  {
    id: 13, title: 'FIGMA TO CODE (UI ENGINEERING)', icon: Layout,
    topics: [
      'Figma interface understanding',
      'Design systems',
      'Spacing & typography systems',
      'Pixel-perfect UI building',
      'Component-based design conversion',
      'Responsive UI conversion',
    ],
    duration: '0.5 weeks', color: '#f472b6',
  },
  {
    id: 14, title: 'AI DEV TOOLS (MODERN DEVELOPER WORKFLOW)', icon: Target,
    topics: [
      'Cursor AI usage',
      'Antigravity tools',
      'AI pair programming',
      'Debugging with AI',
      'Code generation workflows',
      'Productivity systems',
    ],
    duration: '0.5 weeks', color: '#e879f9',
  },
  {
    id: 15, title: 'PRISMA ORM (ADVANCED DATABASE TOOLING)', icon: Layers,
    topics: [
      'ORM architecture',
      'Prisma setup',
      'Schema modeling',
      'Migrations',
      'Relations',
      'Prisma with PostgreSQL/MongoDB',
      'Query optimization basics',
    ],
    duration: '0.5 weeks', color: '#06b6d4',
  },
  {
    id: 16, title: 'CUSTOM LLMs + AI SYSTEMS', icon: Terminal,
    topics: [
      'OpenAI API integration',
      'Prompt engineering',
      'Ollama local models',
      'Hugging Face models',
      'Hosting your own models',
      'Chatbot systems',
      'Voice generation system',
      'Voice cloning project',
      'AI pipelines',
    ],
    duration: '1.5 weeks', color: '#8b5cf6',
  },
  {
    id: 17, title: 'i18n + REACT QUERY', icon: Layers,
    topics: [
      'Internationalization (multi-language apps)',
      'Translation systems',
      'React Query: caching, background fetching, synchronization, mutation system',
    ],
    duration: '0.5 weeks', color: '#22d3ee',
  },
  {
    id: 18, title: 'DOCKER (ADVANCED DEVOPS BASICS)', icon: Server,
    topics: [
      'Containers architecture',
      'Docker images vs containers',
      'Dockerfile creation',
      'Docker compose',
      'Networking basics',
      'Deployment containerization',
    ],
    duration: '0.5 weeks', color: '#2496ed',
  },
  {
    id: 19, title: 'STRIPE (PRODUCTION PAYMENT SYSTEM)', icon: Award,
    topics: [
      'Payment flow architecture',
      'Stripe checkout sessions',
      'Subscription systems',
      'Webhooks system',
      'Billing automation',
      'Secure payment design',
    ],
    duration: '0.5 weeks', color: '#6366f1',
  },
  {
    id: 20, title: 'GOOGLE STITCH (UI/AI TOOL)', icon: Target,
    topics: [
      'UI generation concepts',
      'AI-based design tools',
      'Workflow integration',
      'Rapid prototyping',
    ],
    duration: '0.5 weeks', color: '#fb923c',
  },
  {
    id: 21, title: 'SYSTEM DESIGN BASICS (FOR JUNIOR DEVELOPERS)', icon: Layers,
    topics: [
      'Scalability basics',
      'Load balancing concept',
      'Caching (Redis basics)',
      'Database scaling overview',
      'Microservices intro',
    ],
    duration: '0.5 weeks', color: '#f59e0b',
  },
  {
    id: 22, title: 'PERFORMANCE OPTIMIZATION', icon: Zap,
    topics: [
      'Frontend optimization',
      'Lazy loading',
      'Code splitting',
      'Image optimization',
      'Backend performance tuning',
    ],
    duration: '0.5 weeks', color: '#84cc16',
  },
  {
    id: 23, title: 'REAL WORLD PROJECT ARCHITECTURE', icon: Rocket,
    topics: [
      'Folder structure standards',
      'API design patterns',
      'State management architecture',
      'Scalable project setup',
      'Production best practices',
    ],
    duration: '1.5 weeks', color: '#a78bfa',
  },
];

export const benefits = [
  { icon: Video,        title: 'Live on Google Meet',         desc: 'Every class is a live Google Meet session — real-time coding, screen sharing, and instant Q&A with your instructor.',   color: '#22d3ee' },
  { icon: Languages,    title: 'Taught Fully in Urdu',        desc: 'All lectures delivered in Urdu. Complex concepts explained clearly in your native language — no confusion, just clarity.', color: '#818cf8' },
  { icon: Code2,        title: 'Real Hands-On Projects',      desc: 'Build actual production-grade apps from scratch. No toy examples — real codebases you can show to employers.',           color: '#34d399' },
  { icon: Briefcase,    title: '1 Month Free Internship',     desc: 'Top-performing students earn a 1-month internship at Spurvance Labs with a verifiable internship certificate.',           color: '#fb923c' },
  { icon: GraduationCap,title: 'Completion Certificate',      desc: 'Earn a verifiable bootcamp completion certificate after finishing the course and presenting your capstone project.',       color: '#f472b6' },
  { icon: Zap,          title: 'Lifetime Session Recordings', desc: 'Every Google Meet session is recorded and shared. Missed a class? Rewatch anytime, as many times as you need.',          color: '#a78bfa' },
];

export const tools = [
  { name: 'React',      color: '#61dafb' }, { name: 'Next.js',    color: '#fff'     },
  { name: 'Node.js',    color: '#6cc24a' }, { name: 'TypeScript', color: '#3178c6'  },
  { name: 'Tailwind',   color: '#38bdf8' }, { name: 'MongoDB',    color: '#47a248'  },
  { name: 'PostgreSQL', color: '#336791' }, { name: 'Git',        color: '#f05032'  },
  { name: 'Docker',     color: '#2496ed' }, { name: 'Vercel',     color: '#fff'     },
  { name: 'Supabase',   color: '#3ecf8e' }, { name: 'Stripe',     color: '#635bff'  },
  { name: 'Prisma',     color: '#5a67d8' }, { name: 'OpenAI',     color: '#10a37f'  },
];

export const projects = [
  { title: 'Portfolio + Blog CMS',          desc: 'Personal site with a full dynamic content management system',            tag: 'Module 1-2', color: '#22d3ee' },
  { title: 'E-Commerce Platform',           desc: 'Full online store with cart, checkout & JazzCash / Stripe payments',    tag: 'Module 3-4', color: '#818cf8' },
  { title: 'Real-time Chat Application',    desc: 'WebSocket-powered messaging system with rooms and notifications',        tag: 'Module 3-5', color: '#34d399' },
  { title: 'Task Management Dashboard',     desc: 'Kanban board with drag-and-drop and team collaboration features',        tag: 'Module 2-4', color: '#fb923c' },
  { title: 'Full Stack SaaS Application',   desc: 'Capstone: subscription-based app with admin panel & payment gateway',   tag: 'Module 6',   color: '#a78bfa' },
];

export const faqs = [
  { q: 'Do I need prior coding experience?',              a: 'Not at all! This bootcamp is for beginners. We start from absolute basics and go step by step to advanced topics.' },
  { q: 'Will the classes be in Urdu?',                     a: 'Yes — all lectures are delivered entirely in Urdu so that every concept is crystal clear to you.' },
  { q: 'On which platform will classes be held?',          a: 'All live sessions will be on Google Meet. Each session will also be recorded and you will receive the recording within 24 hours.' },
  { q: 'What is the class schedule?',                      a: 'First 2 months: every day (except Friday and Sunday) from 9 PM to 11 PM. Third month: Friday will also be included and Sunday will have an extended session (more than 2 hours).' },
  { q: 'How does installment payment work?',               a: 'You can pay PKR 20,000 in 3 monthly installments. First installment at enrollment time, the rest at the beginning of each following month.' },
  { q: 'When will I receive the certificate?',             a: 'At the end of the bootcamp, after presenting your capstone project, you will be given a verifiable completion certificate. Top students will also receive a 1-month free internship.' },
  { q: 'What if I miss a class?',                          a: 'No problem — every session is recorded and you can watch whenever you want. Lifetime access.' },
];